#ifndef TRANSPORT_MPI_TAGS_H
#define TRANSPORT_MPI_TAGS_H

#define TRANSPORT_MPI_SIZE_REQUEST_TAG  0
#define TRANSPORT_MPI_DATA_REQUEST_TAG  1
#define TRANSPORT_MPI_SIZE_RESPONSE_TAG 2
#define TRANSPORT_MPI_DATA_RESPONSE_TAG 3

#endif
