language: c++

git:
  depth: 5

os: linux

matrix:
  include:
    # Ubuntu Xenial
    - dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - automake
            - bzip2
            - g++-9
            - gfortran-9
            - libltdl-dev
            - libsnappy-dev
            - libtool-bin
            - pkg-config
            - python3-pip
            - wget
          update: true
      env:
        - C_COMPILER=gcc-9
        - CXX_COMPILER=g++-9
        - FORT_COMPILER=gfortran-9
      script:
        - travis_wait 20 contrib/travis/build_and_test.sh
    # Ubuntu Focal
    - dist: focal
      addons:
        apt:
          packages:
            - automake
            - bzip2
            - g++-9
            - gfortran-9
            - libltdl-dev
            - libsnappy-dev
            - libtool-bin
            - pkg-config
            - python3-pip
            - wget
          update: true
      env:
        - C_COMPILER=gcc-9
        - CXX_COMPILER=g++-9
        - FORT_COMPILER=gfortran-9
      script:
        - travis_wait 20 contrib/travis/build_and_test.sh
    # CentOS 7
    - addons:
        apt:
          update: false
      services: docker
      env:
        - C_COMPILER=gcc
        - CXX_COMPILER=g++
        - FORT_COMPILER=gfortran
        - DOCKER_IMAGE=centos:7
      script:
        - travis_wait 20 docker run --rm --privileged --cap-add=SYS_ADMIN -v $(realpath .):/hxhim -w /hxhim "${DOCKER_IMAGE}" bash -c contrib/travis/centos7.sh
    # CentOS 8
    - addons:
        apt:
          update: false
      services: docker
      env:
        - C_COMPILER=gcc
        - CXX_COMPILER=g++
        - FORT_COMPILER=gfortran
        - DOCKER_IMAGE=centos:8
      script:
        - travis_wait 20 docker run --rm --privileged --cap-add=SYS_ADMIN -v $(realpath .):/hxhim -w /hxhim "${DOCKER_IMAGE}" bash -c contrib/travis/centos8.sh
