name: HXHIM

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        container: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:21.04", "centos:7", "centos:8"]
        async_puts: ["On", "Off"]
        mpi: ["openmpi", "mpich"]

    env:
      BUILD_NAME: "build"
      SWHOME: "/tmp"

    container:
      image: ${{matrix.container}}

    steps:
    - uses: actions/checkout@v2

    - name: Get Ubuntu Packages
      if: startsWith(matrix.container, 'ubuntu:')
      run: |
        contrib/ci/ubuntu.sh ${{matrix.mpi}}
        contrib/ci/ga-set-env.sh "CC=$(which gcc-11)" "CXX=$(which g++-11)"

    - name: Get CentOS 7 Packages
      if: matrix.container == 'centos:7'
      run: |
        source contrib/ci/centos7.sh ${{matrix.mpi}}
        contrib/ci/ga-set-env.sh "CC=$(which gcc)" "CXX=$(which g++)"

    - name: Get CentOS 8 Packages
      if: matrix.container == 'centos:8'
      run: |
        source contrib/ci/centos8.sh ${{matrix.mpi}}
        contrib/ci/ga-set-env.sh "CC=$(which gcc)" "CXX=$(which g++)"

    - name: Build Dependencies
      run: |
        source contrib/hxhim_dependencies.sh --OFI --NO_ROCKSDB --NO_JEMALLOC "${HOME}" "${BUILD_NAME}" "${SWHOME}" "$(nproc --all)" CC="${CC}" CXX="${CXX}"
        contrib/ci/ga-set-env.sh

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel "$(nproc --all)"

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        if [[ "${{matrix.async_puts}}" == "On" ]]; then export HXHIM_START_ASYNC_PUTS_AT=32768; fi
        mpirun -np 1 ${ALLOW_RUN_AS_ROOT} test/googletest
      env:
        GTEST_COLOR: 1
        ALLOW_RUN_AS_ROOT: ${{matrix.mpi == 'openmpi' && '--allow-run-as-root' || ''}}

    - name: Install
      run: |
        cd ${{github.workspace}}/build
        make install
